### ISSUE TITLE
Виджет app\modules\fias\widgets\autocomplete\Autocomplete

### ISSUE THREAD

**Issue by redragon** [solbianca/yii2-fias#1]
Неверное обращение к виджету. `<?= solbianca\fias\widgets\autocomplete\Autocomplete::widget() ?> `Так работает

**Comment by solbianca** [comment]
Сорри. Данный репозиторий больше не поддерживается. Могу лишь посоветовать посмотреть в сторону форка https://github.com/b059ae/yii2-fias . По комиттам видно, что довольно активно допиливает модуль.
